### ISSUE TITLE
Problem with GetUser (CreateUser) with new version of RabbitMQ 3.9.x

### ISSUE THREAD

**Issue by granstam-dev** [EasyNetQ/EasyNetQ.Management.Client#150]
Hi,
I'm getting an exception when fetching/creating user on the new RabbitMQ version 3.9.x using EasyNetQ.Management.Client version 1.4.0 (I have also tried older versions of the EasyNetQ.Management.Client with the same result).
It works without any problem on the latest 3.8 version (3.8.22) of RabbitMQ.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'tags', line 1, position 159.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at EasyNetQ.Management.Client.ManagementClient.<>c__86`1.<DeserializeResponseAsync>b__86_0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyNetQ.Management.Client.ManagementClient.<CreateUserAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyNetQ.Management.Client.ManagementClientExtensions.CreateUser(IManagementClient source, UserInfo userInfo, CancellationToken cancellationToken)

**Comment by granstam-dev** [comment]
The exception is thrown because the RabbitMQ team has change the "tags" from a comma delimited string (3.8.x) to a list of strings (3.9.x).

Get method:
http://127.0.0.1:15672/api/users/mikey

Response from 3.8.x versions 
{"name":"mikey","password_hash":"mgxUtK3CvLQ3sJQJWJjiaekdoUGRe+0RjL/bqqnKj5eensAR","hashing_algorithm":"rabbit_password_hashing_sha256","tags":"administrator,management","limits":{}}

Response from 3.9.x versions
{"name":"mikey","password_hash":"eGrRcuwXwcjazLlGWYgjD9UHA3fey3B8I8xgQVHiKTHm+w3Q","hashing_algorithm":"rabbit_password_hashing_sha256","tags":["administrator","management"],"limits":{}}

**Comment by davidefasolosalvagnini** [comment]
Is there any plan to solve this issue?

**Comment by troglas** [comment]
Is there any plan to solve this?
Is this repository out of support and should not be used ?

**Comment by kmatyaszek** [comment]
I have already resolved this issue in #153. It works with new and older version of RabbitMQ.
