### ISSUE TITLE
In RabbitMQ 3.12.10 Queue.ConsumerDetails[].ChannelDetail.Name can be null

### ISSUE THREAD

**Issue by inikulshin** [EasyNetQ/EasyNetQ.Management.Client#306]
In **RabbitMQ 3.12.10** (+ EasyNetQ.Management.Client 3.0.0-alpha5) `Queue.ConsumerDetails[].ChannelDetail.Name` can be null:

```
System.ArgumentNullException: [NullGuard] Name is null.
Parameter name: Name
   at EasyNetQ.Management.Client.Model.ChannelDetail..ctor(String Name, Int32 Number, String User, String ConnectionName, Int32 PeerPort, String PeerHost, String Node)
   at .ctor(Object[] )
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.CreateObject(ReadStackFrame& frame)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](JsonElement element, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at EasyNetQ.Management.Client.Serialization.EmptyArrayAsDefaultConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.ReadConstructorArgumentsWithContinuation(ReadStack& state, Utf8JsonReader& reader, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.ReadConstructorArgumentsWithContinuation(ReadStack& state, Utf8JsonReader& reader, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.<ReadFromStreamAsync>d__76`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyNetQ.Management.Client.ManagementClient.<GetAsync>d__108`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyNetQ.Management.Client.ManagementClientExtensions.GetQueue(IManagementClient client, Vhost vhost, String queueName, LengthsCriteria lengthsCriteria, RatesCriteria ratesCriteria, CancellationToken cancellationToken)
```

**Comment by inikulshin** [comment]
Ok, the issue is different. @Pliner, thanks for asking a reproduction. :)

I caught an exception from `ReadFromJsonAsync`:

`System.Text.Json.JsonException: EasyNetQ JSON scheme doesn't match actual RabbitMQ response content: {"garbage_collection":{"max_heap_size":-1,"min_bin_vheap_size":-1,"min_heap_size":-1,"fullsweep_after":-1,"minor_gcs":-1},"consumer_details":[{"arguments":{},"channel_details":{},"ack_required":true,"active":true,"activity_status":"up","consumer_tag":"1","consumer_timeout":"undefined","exclusive":false,"prefetch_count":0,"queue":{"name":"vsb.topic=Filtering_13","vhost":"TLS_B"}}],"arguments":{"x-max-priority":4},"auto_delete":false,"deliveries":[],"durable":true,"exclusive":false,"incoming":[],"name":"vsb.topic=Filtering_13","node":"rabbit@localhost","type":"classic","vhost":"TLS_B"}
`

The interesting part of it is `"channel_details":{}`

I think, we can fix `EmptyArrayAsDefaultConverter` with 

```
            case { ValueKind: JsonValueKind.Object } when jsonElement.EnumerateObject().Any():
                return jsonElement.Deserialize<T>(options);

            case { ValueKind: JsonValueKind.Object }:
                return default;
```

What do you think?

**Comment by inikulshin** [comment]
The same happened to `"arguments": {}`, which is also defined with `EmptyArrayAsDefaultConverter` converter

```
    [property: JsonConverter(typeof(EmptyArrayAsDefaultConverter<ConsumerArguments>))]
    ConsumerArguments? Arguments,
```

Formatted response:

```
{
  "garbage_collection": {
    "max_heap_size": -1,
    "min_bin_vheap_size": -1,
    "min_heap_size": -1,
    "fullsweep_after": -1,
    "minor_gcs": -1
  },
  "consumer_details": [
    {
      "arguments": {},
      "channel_details": {},
      "ack_required": true,
      "active": true,
      "activity_status": "up",
      "consumer_tag": "1",
      "consumer_timeout": "undefined",
      "exclusive": false,
      "prefetch_count": 0,
      "queue": {
        "name": "vsb.topic=Filtering_13",
        "vhost": "TLS_B"
      }
    }
  ],
  "arguments": {
    "x-max-priority": 4
  },
  "auto_delete": false,
  "deliveries": [],
  "durable": true,
  "exclusive": false,
  "incoming": [],
  "name": "vsb.topic=Filtering_13",
  "node": "rabbit@localhost",
  "type": "classic",
  "vhost": "TLS_B"
}
```

**Comment by inikulshin** [comment]
Fixed.
