### ISSUE TITLE
Creating a VHOST doesn't check for the correct status codes (201=Created)

### ISSUE THREAD

**Issue by zidad** [EasyNetQ/EasyNetQ.Management.Client#55]
Status 201-Created should not throw an exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> EasyNetQ.Management.Client.UnexpectedHttpStatusCodeException: Unexpected Status Code: 201 Created
   at EasyNetQ.Management.Client.ManagementClient.Put(String path)
   at EasyNetQ.Management.Client.ManagementClient.CreateVirtualHost(String virtualHostName)
   at AerData.Bus.Host.Tasks.RabbitMqRecreateVHost.Run(RabbitMqConnectionSettings options, CancellationToken token)

**Comment by luigiberrettini** [comment]
Please check if it stills happens and provide further details with links to the source code points where it fails.

**Comment by Pliner** [comment]
Not relevant anymore.

https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/master/Source/EasyNetQ.Management.Client/ManagementClient.cs#L691
