### ISSUE TITLE
GetQueue fails when consumer attached

### ISSUE THREAD

**Issue by euronay** [EasyNetQ/EasyNetQ.Management.Client#65]
Hi,

I've found an issue where the GetQueue is throwing an error deserialising the response from the Rabbit API when a consumer is attached. The error is:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'consumer_details[0].arguments.x-credit', line 1, position 47.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at EasyNetQ.Management.Client.ManagementClient.DeserializeResponse[T](HttpWebResponse response)
   at EasyNetQ.Management.Client.ManagementClient.Get[T](String path, Object[] queryObjects)
   at EasyNetQ.Management.Client.ManagementClient.GetQueue(String queueName, Vhost vhost, GetLengthsCriteria lengthsCriteria, GetRatesCriteria ratesCriteria)
```

This is only thrown when I have a consumer attached to the queue. I've narrowed down the issue to the `arguments` in `consumer_details` section of the json returned from `api/queues/%2f/<queuename>` , there is an `x-credit` argument with an array , meaning the arguments can't be deserialized into a `Dictionary<string,String>`:

```json
{
    "consumer_details": [
        {
            "arguments": {
                "x-credit": {
                    "credit": 0,
                    "drain": false
                }
            },
```

I can resolve this by changing Model\Argument.cs from:

```csharp
public class Arguments : Dictionary<string, string>
```
to
```csharp
public class Arguments : Dictionary<string, object>
```

However, I'm not sure what can be included in the `arguments` section of the API call - and I cannot find a definitive reference anywhere. 

I'm using Rabbit MQ server 3.7.0-rc2

Thanks

**Comment by luigiberrettini** [comment]
Can you check with the code on master if it still happens?

**Comment by euronay** [comment]
I checked this and it was still happening. I've created a new PR #78 against master.
